theme:
  - osuny-alumni-theme
  - osuny-campus-art-mediterrannee-footer
  - osuny
_merge: deep
params:
  campus_art_mediterrannee_footer:
    logo:
      suffix: "-white"
  summary:
    position: hero
  search:
    active: true
    positions:
      - alumni
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  breadcrumb:
    position: none
  persons:
    index:
      layout: grid
      options:
        cohorts: true
    single:
      meta:
        position: hero
  alumni:
    menu:
      programs:
        exclude_children: true
  image_sizes:
    sections:
      persons:
        hero_single:
          mobile:   200
          tablet:   800
          desktop:  800
        item:
          mobile:   80
          tablet:   100
          desktop:  400
        layouts:
          grid:
            mobile:   90
            tablet:   220
            desktop:  400