[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/audrey-ziane/programs/"
to = "/equipe/audrey-ziane/programs/"

[[redirects]]
from = "/elias-hosni/"
to = "/equipe/elias-hosni/"

[[redirects]]
from = "/categories/agentes-administratifs-ba/service-vie-etudiante-et-egalite-des-chances/"
to = "/equipe/categories/agentes-administratifs-ba/pole-direction-des-etudes/service-vie-etudiante-et-egalite-des-chances/"

[[redirects]]
from = "/antonella-minchella/"
to = "/equipe/antonella-minchella/"

[[redirects]]
from = "/alexandre-fontanie/"
to = "/equipe/alexandre-fontanie/"

[[redirects]]
from = "/lisa-obrecht/"
to = "/equipe/lisa-obrecht/"

[[redirects]]
from = "/frederic-fredout/programs/"
to = "/equipe/frederic-fredout/programs/"

[[redirects]]
from = "/justine-porcheron/"
to = "/equipe/justine-porcheron/"

[[redirects]]
from = "/2026-03-27-appel-a-candidature--www-beauxartsdemarseille-fr/"
to = "/actualites/2026-03-27-appel-a-candidature--www-beauxartsdemarseille-fr/"

[[redirects]]
from = "/fabian-toueix/"
to = "/equipe/fabian-toueix/"

[[redirects]]
from = "/celia-martin/"
to = "/equipe/celia-martin/"

[[redirects]]
from = "/cecile-marie-castanet/programs/"
to = "/equipe/cecile-marie-castanet/programs/"

[[redirects]]
from = "/clare-poolman/"
to = "/equipe/clare-poolman/"

[[redirects]]
from = "/camille-noel/"
to = "/equipe/camille-noel/"

[[redirects]]
from = "/vanessa-brito/"
to = "/equipe/vanessa-brito/"

[[redirects]]
from = "/francoise-buadas/"
to = "/equipe/francoise-buadas/"

[[redirects]]
from = "/equipe/categories/agentes-ifamm/professeures-ifamm/"
to = "/equipe/categories/professeures-ifamm/"

[[redirects]]
from = "/maymouna-baradji/"
to = "/equipe/maymouna-baradji/"

[[redirects]]
from = "/equipe/categories/agentes-administratifs-ba/service-vie-etudiante-et-egalite-des-chances/"
to = "/equipe/categories/agentes-administratifs-ba/pole-direction-des-etudes/service-vie-etudiante-et-egalite-des-chances/"

[[redirects]]
from = "/may-pecher/"
to = "/equipe/may-pecher/"

[[redirects]]
from = "/2026-01-27-passages-elementaires/"
to = "/actualites/2026-01-27-passages-elementaires/"

[[redirects]]
from = "/carla-lloret/"
to = "/equipe/carla-lloret/"

[[redirects]]
from = "/louison-gallego/"
to = "/equipe/louison-gallego/"

[[redirects]]
from = "/celia-charles/"
to = "/equipe/celia-charles/"

[[redirects]]
from = "/saliha-hamlaoui/"
to = "/equipe/saliha-hamlaoui/"

[[redirects]]
from = "/anna-mandeix/"
to = "/equipe/anna-mandeix/"

[[redirects]]
from = "/laurence-renucci/"
to = "/equipe/laurence-renucci/"

[[redirects]]
from = "/categories/professeurs-ba/professeure-artiste-designer/"
to = "/equipe/categories/professeurs-ba/professeure-artiste-designer/"

[[redirects]]
from = "/celie-miloch/"
to = "/equipe/celie-miloch/"

[[redirects]]
from = "/theo-anthouard/"
to = "/equipe/theo-anthouard/"

[[redirects]]
from = "/karine-santi-weil/programs/"
to = "/equipe/karine-santi-weil/programs/"

[[redirects]]
from = "/miguel-angel-canchari/"
to = "/equipe/miguel-angel-canchari/"

[[redirects]]
from = "/dafy-adriano-razafindrazaka/"
to = "/equipe/dafy-adriano-razafindrazaka/"

[[redirects]]
from = "/frederic-fredout/"
to = "/equipe/frederic-fredout/"

[[redirects]]
from = "/lila-crnogorac/"
to = "/equipe/lila-crnogorac/"

[[redirects]]
from = "/equipe/categories/professeures-cpbm/"
to = "/categories/professeures-cpbm/"

[[redirects]]
from = "/miao-luo/"
to = "/equipe/miao-luo/"

[[redirects]]
from = "/2025-11-19-residence-de-laurence-merle-au-18-a-marrakech-maroc--www-beauxartsdemarseille-fr/"
to = "/actualites/2025-11-19-residence-de-laurence-merle-au-18-a-marrakech-maroc--www-beauxartsdemarseille-fr/"

[[redirects]]
from = "/jianghao-liu/"
to = "/equipe/jianghao-liu/"

[[redirects]]
from = "/liza-rolland/"
to = "/equipe/liza-rolland/"

[[redirects]]
from = "/rafael-garcia-lara/"
to = "/equipe/rafael-garcia-lara/"

[[redirects]]
from = "/cara-schmitz/"
to = "/equipe/cara-schmitz/"

[[redirects]]
from = "/barbara-pereira-magalhaes/"
to = "/equipe/barbara-pereira-magalhaes/"

[[redirects]]
from = "/adriana-lara/"
to = "/equipe/adriana-lara/"

[[redirects]]
from = "/equipe-administrative/"
to = "/equipe/equipe-administrative/"

[[redirects]]
from = "/alexandre-katsenis/"
to = "/equipe/alexandre-katsenis/"

[[redirects]]
from = "/blanche-coquerel/"
to = "/equipe/blanche-coquerel/"

[[redirects]]
from = "/2025-12-04-some-places-for-a-duoe/"
to = "/actualites/2025-12-04-some-places-for-a-duoe/"

[[redirects]]
from = "/sebastien-vanhulst/"
to = "/equipe/sebastien-vanhulst/"

[[redirects]]
from = "/denis-prisset/"
to = "/equipe/denis-prisset/"

[[redirects]]
from = "/zhiting-fu/"
to = "/equipe/zhiting-fu/"

[[redirects]]
from = "/frederic-pradeau/roles/"
to = "/equipe/frederic-pradeau/roles/"

[[redirects]]
from = "/categories/agentes-administratifs-ba/service-communication/"
to = "/equipe/categories/agentes-administratifs-ba/service-communication/"

[[redirects]]
from = "/severina-ivanova/"
to = "/equipe/severina-ivanova/"

[[redirects]]
from = "/josephine-gelis/"
to = "/equipe/josephine-gelis/"

[[redirects]]
from = "/beaux-arts-de-marseille/"
to = "/ecoles/beaux-arts-de-marseille/"

[[redirects]]
from = "/manon-torne-sistero/"
to = "/equipe/manon-torne-sistero/"

[[redirects]]
from = "/clemence-bruno/"
to = "/equipe/clemence-bruno/"

[[redirects]]
from = "/yahnis-rocailleux/"
to = "/equipe/yahnis-rocailleux/"

[[redirects]]
from = "/vanessa-brito/publications/"
to = "/equipe/vanessa-brito/publications/"

[[redirects]]
from = "/ariadna-chavez-sierra/"
to = "/equipe/ariadna-chavez-sierra/"

[[redirects]]
from = "/sasha-capitaine/"
to = "/equipe/sasha-capitaine/"

[[redirects]]
from = "/francoise-buadas/programs/"
to = "/equipe/francoise-buadas/programs/"

[[redirects]]
from = "/2025-12-04-lalchimie-collective/"
to = "/actualites/2025-12-04-lalchimie-collective/"

[[redirects]]
from = "/gabriel-montane/"
to = "/equipe/gabriel-montane/"

[[redirects]]
from = "/azalina-mouhidini/"
to = "/equipe/azalina-mouhidini/"

[[redirects]]
from = "/lila-el-guelay/"
to = "/equipe/lila-el-guelay/"

[[redirects]]
from = "/thibaut-sy/"
to = "/equipe/thibaut-sy/"

[[redirects]]
from = "/samuel-gratacap/"
to = "/equipe/samuel-gratacap/"

[[redirects]]
from = "/theo-soultan/"
to = "/equipe/theo-soultan/"

[[redirects]]
from = "/aure-de-thieulloy/"
to = "/equipe/aure-de-thieulloy/"

[[redirects]]
from = "/marcos-uriondo/"
to = "/equipe/marcos-uriondo/"

[[redirects]]
from = "/aurelien-mathis/"
to = "/equipe/aurelien-mathis/"

[[redirects]]
from = "/denis-prisset/publications/"
to = "/equipe/denis-prisset/publications/"

[[redirects]]
from = "/2025-12-04-les-silences-sont-des-repits/"
to = "/actualites/2025-12-04-les-silences-sont-des-repits/"

[[redirects]]
from = "/juliette-duval/"
to = "/equipe/juliette-duval/"

[[redirects]]
from = "/julie-chevassus/"
to = "/equipe/julie-chevassus/"

[[redirects]]
from = "/lise-guehenneux/"
to = "/equipe/lise-guehenneux/"

[[redirects]]
from = "/frederic-pradeau/"
to = "/equipe/frederic-pradeau/"

[[redirects]]
from = "/victor-giroux/"
to = "/equipe/victor-giroux/"

[[redirects]]
from = "/nicolas-pilard/"
to = "/equipe/nicolas-pilard/"

[[redirects]]
from = "/mahira-doume/"
to = "/equipe/mahira-doume/"

[[redirects]]
from = "/categories/professeurs-ba/classe-preparatoire/"
to = "/equipe/categories/professeurs-ba/classe-preparatoire/"

[[redirects]]
from = "/sara-kiwan/"
to = "/equipe/sara-kiwan/"

[[redirects]]
from = "/frederic-pradeau/programs/"
to = "/equipe/frederic-pradeau/programs/"

[[redirects]]
from = "/zoe-saudrais/"
to = "/equipe/zoe-saudrais/"

[[redirects]]
from = "/selma-thies/"
to = "/equipe/selma-thies/"

[[redirects]]
from = "/ix-dartayre/"
to = "/equipe/ix-dartayre/"

[[redirects]]
from = "/adem-horrigue/"
to = "/equipe/adem-horrigue/"

[[redirects]]
from = "/hosana-schornstein/"
to = "/equipe/hosana-schornstein/"

[[redirects]]
from = "/emma-cambier/"
to = "/equipe/emma-cambier/"

[[redirects]]
from = "/jeanne-rocher/"
to = "/equipe/jeanne-rocher/"

[[redirects]]
from = "/songzi-yang/"
to = "/equipe/songzi-yang/"

[[redirects]]
from = "/vanessa-brito/programs/"
to = "/equipe/vanessa-brito/programs/"

[[redirects]]
from = "/alix-vigouroux/"
to = "/equipe/alix-vigouroux/"

[[redirects]]
from = "/lulea-joachim-tran/"
to = "/equipe/lulea-joachim-tran/"

[[redirects]]
from = "/pierre-laurent-cassiere/"
to = "/equipe/pierre-laurent-cassiere/"

[[redirects]]
from = "/baptiste-mauriat/"
to = "/equipe/baptiste-mauriat/"

[[redirects]]
from = "/aure-de-thieulloy/roles/"
to = "/equipe/aure-de-thieulloy/roles/"

[[redirects]]
from = "/equipe/categories/agentes-ifamm/formateurtrices-cfpi/"
to = "/equipe/categories/formateurtrices-cfpi/"

[[redirects]]
from = "/equipe/categories/agentes-ifamm/"
to = "/categories/agentes-ifamm/"

[[redirects]]
from = "/maxime-lelasseux/"
to = "/equipe/maxime-lelasseux/"

[[redirects]]
from = "/nicolas-pilard/programs/"
to = "/equipe/nicolas-pilard/programs/"

[[redirects]]
from = "/nadia-slimani/"
to = "/equipe/nadia-slimani/"

[[redirects]]
from = "/lolita-perez/"
to = "/equipe/lolita-perez/"

[[redirects]]
from = "/denis-prisset/programs/"
to = "/equipe/denis-prisset/programs/"

[[redirects]]
from = "/alice-le-du/"
to = "/equipe/alice-le-du/"

[[redirects]]
from = "/appel-a-candidature/"
to = "/actualites/appel-a-candidature/"

[[redirects]]
from = "/amaria-boujon/"
to = "/equipe/amaria-boujon/"

[[redirects]]
from = "/meriem-kadi/"
to = "/equipe/meriem-kadi/"

[[redirects]]
from = "/zoe-sinatti/"
to = "/equipe/zoe-sinatti/"

[[redirects]]
from = "/pierre-laurent-cassiere/programs/"
to = "/equipe/pierre-laurent-cassiere/programs/"

[[redirects]]
from = "/alwen-raguenel/"
to = "/equipe/alwen-raguenel/"

[[redirects]]
from = "/zilien/"
to = "/equipe/zilien/"

[[redirects]]
from = "/garance-gambin/"
to = "/equipe/garance-gambin/"

[[redirects]]
from = "/julia-bonich/"
to = "/equipe/julia-bonich/"

[[redirects]]
from = "/renata-alves/"
to = "/equipe/renata-alves/"

[[redirects]]
from = "/categories/agentes-administratifs-ba/"
to = "/equipe/categories/agentes-administratifs-ba/"

[[redirects]]
from = "/margo-le-corf/"
to = "/equipe/margo-le-corf/"

[[redirects]]
from = "/lara-bellot/"
to = "/equipe/lara-bellot/"

[[redirects]]
from = "/jolan-nestor-garcia-lecointe/"
to = "/equipe/jolan-nestor-garcia-lecointe/"

[[redirects]]
from = "/categories/professeurs-ba/philosophie-histoire-et-theorie-de-lart-du-design/"
to = "/equipe/categories/professeurs-ba/philosophie-histoire-et-theorie-de-lart-du-design/"

[[redirects]]
from = "/kylian-said-zeggane/"
to = "/equipe/kylian-said-zeggane/"

[[redirects]]
from = "/laurence-merle/"
to = "/equipe/laurence-merle/"

[[redirects]]
from = "/temitayo-olalekan/"
to = "/equipe/temitayo-olalekan/"

[[redirects]]
from = "/chloe-rozier/"
to = "/equipe/chloe-rozier/"

[[redirects]]
from = "/etta-marthe-wunsch/"
to = "/equipe/etta-marthe-wunsch/"

[[redirects]]
from = "/nicolas-sanchez-garrido/"
to = "/equipe/nicolas-sanchez-garrido/"

[[redirects]]
from = "/paul-escamez/"
to = "/equipe/paul-escamez/"

[[redirects]]
from = "/milan-giraud/"
to = "/equipe/milan-giraud/"

[[redirects]]
from = "/martin-mesnier/"
to = "/equipe/martin-mesnier/"

[[redirects]]
from = "/valentin-vert/"
to = "/equipe/valentin-vert/"

[[redirects]]
from = "/clara-guilbert/"
to = "/equipe/clara-guilbert/"

[[redirects]]
from = "/categories/agentes-ifamm/professeures-ifamm/"
to = "/equipe/categories/professeures-ifamm/"

[[redirects]]
from = "/johan-rochont/"
to = "/equipe/johan-rochont/"

[[redirects]]
from = "/karine-santi-weil/"
to = "/equipe/karine-santi-weil/"

[[redirects]]
from = "/camille-derniaux/"
to = "/equipe/camille-derniaux/"

[[redirects]]
from = "/clovis-mwilambwe-ngoy/"
to = "/equipe/clovis-mwilambwe-ngoy/"

[[redirects]]
from = "/janice-keriven/"
to = "/equipe/janice-keriven/"

[[redirects]]
from = "/sophie-andry/"
to = "/equipe/sophie-andry/"

[[redirects]]
from = "/anouch-basbous/"
to = "/equipe/anouch-basbous/"

[[redirects]]
from = "/evane-priou/"
to = "/equipe/evane-priou/"

[[redirects]]
from = "/oceane-pilette/"
to = "/equipe/oceane-pilette/"

[[redirects]]
from = "/luc-jeandheur/"
to = "/equipe/luc-jeandheur/"

[[redirects]]
from = "/2025-12-04-ix-dartayre/"
to = "/actualites/2025-12-04-ix-dartayre/"

[[redirects]]
from = "/ryan-jamali/"
to = "/equipe/ryan-jamali/"

[[redirects]]
from = "/cassandre-thevenier/"
to = "/equipe/cassandre-thevenier/"

[[redirects]]
from = "/charles-david-gnangoran/"
to = "/equipe/charles-david-gnangoran/"

[[redirects]]
from = "/lucas-delemar/"
to = "/equipe/lucas-delemar/"

[[redirects]]
from = "/lise-guehenneux/publications/"
to = "/equipe/lise-guehenneux/publications/"

[[redirects]]
from = "/baptist-gheeraert/"
to = "/equipe/baptist-gheeraert/"

[[redirects]]
from = "/equipe/categories/professeures-cpbm/bois/"
to = "/categories/professeures-cpbm/bois/"

[[redirects]]
from = "/hiver-du-printemps/"
to = "/actualites/hiver-du-printemps/"

[[redirects]]
from = "/samuel-gratacap/programs/"
to = "/equipe/samuel-gratacap/programs/"

[[redirects]]
from = "/categories/agentes-administratifs-ba/pole-direction-des-etudes/service-vie-etudiante-et-egalite-des-chances/"
to = "/equipe/categories/agentes-administratifs-ba/pole-direction-des-etudes/service-vie-etudiante-et-egalite-des-chances/"

[[redirects]]
from = "/juliette-rougier/"
to = "/equipe/juliette-rougier/"

[[redirects]]
from = "/dennis-tredy/programs/"
to = "/equipe/dennis-tredy/programs/"

[[redirects]]
from = "/categories/formateurtrices-cfpi/"
to = "/equipe/categories/formateurtrices-cfpi/"

[[redirects]]
from = "/categories/agentes-ifamm/formateurtrices-cfpi/"
to = "/equipe/categories/formateurtrices-cfpi/"

[[redirects]]
from = "/dennis-tredy/"
to = "/equipe/dennis-tredy/"

[[redirects]]
from = "/categories/professeurs-ba/langue-vivante/"
to = "/equipe/categories/professeurs-ba/langue-vivante/"

[[redirects]]
from = "/lise-guehenneux/programs/"
to = "/equipe/lise-guehenneux/programs/"

[[redirects]]
from = "/agnes-martel/programs/"
to = "/equipe/agnes-martel/programs/"

[[redirects]]
from = "/capucine-parmentier/"
to = "/equipe/capucine-parmentier/"

[[redirects]]
from = "/categories/agentes-administratifs-ba/pole-direction-des-etudes/"
to = "/equipe/categories/agentes-administratifs-ba/pole-direction-des-etudes/"

[[redirects]]
from = "/sidonie-jaillet/"
to = "/equipe/sidonie-jaillet/"

[[redirects]]
from = "/gabrielle-alexandre/"
to = "/equipe/gabrielle-alexandre/"

[[redirects]]
from = "/cecile-marie-castanet/publications/"
to = "/equipe/cecile-marie-castanet/publications/"

[[redirects]]
from = "/oliver-salway/"
to = "/equipe/oliver-salway/"

[[redirects]]
from = "/melisa-yagmur-saydi/"
to = "/equipe/melisa-yagmur-saydi/"

[[redirects]]
from = "/valentin-saez-1/"
to = "/equipe/valentin-saez-1/"

[[redirects]]
from = "/categories/agentes-administratifs-ba/service-communication/responsable-4/"
to = "/equipe/categories/agentes-administratifs-ba/service-communication/responsable-4/"

[[redirects]]
from = "/lily-barotte/"
to = "/equipe/lily-barotte/"

[[redirects]]
from = "/nadia-slimani/actualites/"
to = "/equipe/nadia-slimani/actualites/"

[[redirects]]
from = "/cyprien-arsac/"
to = "/equipe/cyprien-arsac/"

[[redirects]]
from = "/lola-sahar/"
to = "/equipe/lola-sahar/"

[[redirects]]
from = "/categories/professeures-ifamm/"
to = "/equipe/categories/professeures-ifamm/"

[[redirects]]
from = "/carla-aouad/"
to = "/equipe/carla-aouad/"

[[redirects]]
from = "/equipe/bernard-giraud/"
to = "/bernard-giraud/"

[[redirects]]
from = "/agnes-martel/"
to = "/equipe/agnes-martel/"

[[redirects]]
from = "/nonna-muller/"
to = "/equipe/nonna-muller/"

[[redirects]]
from = "/luc-jeandheur/programs/"
to = "/equipe/luc-jeandheur/programs/"

[[redirects]]
from = "/2026-04-13-appel-a-candidature/"
to = "/actualites/2026-04-13-appel-a-candidature/"

[[redirects]]
from = "/yizhen-chen/"
to = "/equipe/yizhen-chen/"

[[redirects]]
from = "/arielle-holtz/"
to = "/equipe/arielle-holtz/"

[[redirects]]
from = "/stella-gercara/"
to = "/equipe/stella-gercara/"

[[redirects]]
from = "/anais-maurel/"
to = "/equipe/anais-maurel/"

[[redirects]]
from = "/marion-serre/"
to = "/equipe/marion-serre/"

[[redirects]]
from = "/tristan-feminier/"
to = "/equipe/tristan-feminier/"

[[redirects]]
from = "/sarah-fageot/"
to = "/equipe/sarah-fageot/"

[[redirects]]
from = "/zadig-robin-1/"
to = "/equipe/zadig-robin-1/"

[[redirects]]
from = "/manon-monchaux/"
to = "/equipe/manon-monchaux/"

[[redirects]]
from = "/audrey-ziane/"
to = "/equipe/audrey-ziane/"

[[redirects]]
from = "/lucien-lejeune/"
to = "/equipe/lucien-lejeune/"

[[redirects]]
from = "/marion-serre/programs/"
to = "/equipe/marion-serre/programs/"

[[redirects]]
from = "/constant-gapp/"
to = "/equipe/constant-gapp/"

[[redirects]]
from = "/celia-leray/"
to = "/equipe/celia-leray/"

[[redirects]]
from = "/adriana-lara/programs/"
to = "/equipe/adriana-lara/programs/"

[[redirects]]
from = "/nathalia-golda-cimia/"
to = "/equipe/nathalia-golda-cimia/"

[[redirects]]
from = "/2025-12-04-reiterer-le-recit-queer-pour-habiter-les-imaginaires/"
to = "/actualites/2025-12-04-reiterer-le-recit-queer-pour-habiter-les-imaginaires/"

[[redirects]]
from = "/cecile-marie-castanet/"
to = "/equipe/cecile-marie-castanet/"

[[redirects]]
from = "/aurelie-arzoine-lafages/"
to = "/equipe/aurelie-arzoine-lafages/"

[[redirects]]
from = "/lise-coti/"
to = "/equipe/lise-coti/"

[[redirects]]
from = "/deborah-maurice/"
to = "/equipe/deborah-maurice/"

[[redirects]]
from = "/julie-dumas/"
to = "/equipe/julie-dumas/"

[[redirects]]
from = "/christian-garre/"
to = "/equipe/christian-garre/"

[[redirects]]
from = "/categories/portraits-pisourd-e/"
to = "/equipe/categories/portraits-pisourd-e/"

[[redirects]]
from = "/miriam-angeli-padilha/"
to = "/equipe/miriam-angeli-padilha/"

